### ISSUE TITLE
Is there a Protobuf example?

### ISSUE THREAD

**Issue by mmendez512** [gnormal/gnorm#134]
My team has a brand new microservice project where we want to generate our go db models and protobuf files (for grpc) directly from the db schema.

On the gnorm site, it mentions we can generate protobufs from templates. I'm just curious if there's a simple example on how to do this.

Thanks.

**Comment by freb** [comment]
I generate a proto file using Gnorm. It outputs message types for each table and additional messages to support the request and response messages for the CRUD RPCs it also generates. If you're just looking for message generation, the template could be paired down.

I'd be happy to prepare a PR for an example if @natefinch is open to accepting it. Otherwise I'm happy to just upload the config and template file here.

**Comment by natefinch** [comment]
I would welcome a PR for generating gRPC. :)

**Comment by mmendez512** [comment]
Thanks @freb!!

**Comment by natefinch** [comment]
hmm, it probably should be in its own repo. I can make one for you.

**Comment by natefinch** [comment]
https://github.com/gnormal/gRPC

**Comment by freb** [comment]
See: https://github.com/gnormal/gRPC/pull/1

**Comment by mmendez512** [comment]
Thanks guys! Going to close out this issue now there's a PR open.
